Fix/matlab cli args
iceberg-project/Rivers pull request #10
Opened 2019-06-13 17:11 UTC by iparask

This pull request changes the tilling matlab script to a function. It allows us to run it from the command line as

```
matlab -r 'tiling_pretraining("image","image_mask")'
```

In addition it checks if `image` and `image_mask` are strings. If not it returns an error.

2019-06-17 13:53 UTC, bspitzbart approved these changes

2019-08-01 14:23 UTC, samiraucsb requested changes

2019-08-01 14:23 UTC, samiradaneshgar commented on src/tiling/tiling_pretraining.m
> +    WriteDir1 = fullfile(pwd, 'tiled multi-page image');
WriteDir1=fullfile(pwd, 'tiled-multi-page-image');

2019-08-01 14:23 UTC, samiradaneshgar commented on src/tiling/tiling_pretraining.m
> +    WriteDir2 = fullfile(pwd, 'tiled multi-page river mask');
WriteDir2 = fullfile(pwd, 'tiled-multi-page-river-mask');

2019-08-01 14:23 UTC, samiradaneshgar commented on src/tiling/tiling_pretraining.m
> +    patch_size=800;
This is input.

2019-08-01 14:23 UTC, samiradaneshgar commented on src/tiling/tiling_pretraining.m
> +    step=400;
This is also an input.

2019-08-10 02:57 UTC, samiraucsb requested changes

2019-08-10 02:57 UTC, samiradaneshgar commented on src/tiling/tiling_pretraining.m
> +    WriteDir1 = fullfile(pwd, 'tiled-multi-page-image', tmp_folder(1));
WriteDir1 = fullfile(pwd, 'tiled-multi-page-image');

2019-08-10 02:57 UTC, samiradaneshgar commented on src/tiling/tiling_pretraining.m
> +    WriteDir2 = fullfile(pwd, 'tiled-multi-page-river-mask', tmp_folder(1));
WriteDir2 = fullfile(pwd, 'tiled-multi-page-river-mask');

2019-08-10 02:57 UTC, samiradaneshgar commented on src/tiling/tiling_pretraining.m
> +
movefile(fullfile(WriteDir1,'*.tif'), fullfile(WriteDir1,tmp_folder(1)));

2019-08-10 02:57 UTC, samiradaneshgar commented on src/tiling/tiling_pretraining.m
> +
movefile(fullfile(WriteDir2,'*.tif'), fullfile(WriteDir2,tmp_folder(1)));

2019-08-10 02:57 UTC, samiradaneshgar commented on src/training/randselect_pretraining.m
> +    movefile(fullfile(FileList1(index(k)).folder, FileList1(index(k)).name), fullfile(WriteDir1, sprintf(FileList1(index(k)).name)));
movefile(fullfile(FileList1(index(k)).folder, FileList1(index(k)).name), fullfile(WriteDir1, sprintf('%.02d.tif', k)));

2019-08-10 02:57 UTC, samiradaneshgar commented on src/training/randselect_pretraining.m
> +    movefile(fullfile(FileList2(k).folder, FileList2(k).name),[WriteDir2 'Test-' FileList2(k).name]);
movefile(fullfile(FileList2(k).folder, FileList2(k).name),[WriteDir2 'Test-' sprintf('%.02d.tif', k)]);

2019-08-10 02:57 UTC, samiradaneshgar commented on src/training/randselect_pretraining.m
> +    movefile(fullfile(FileList1(index(k)).folder, FileList1(index(k)).name), fullfile(WriteDir3, sprintf(FileList1(index(k)).name)));
movefile(fullfile(FileList1(index(k)).folder, FileList1(index(k)).name), fullfile(WriteDir3, sprintf('%.02d.tif', k)));

2019-08-10 02:57 UTC, samiradaneshgar commented on src/training/randselect_pretraining.m
> +   movefile(fullfile(FileList2(k).folder, FileList2(k).name),[WriteDir4 'Test-' FileList2(k).name]);
movefile(fullfile(FileList2(k).folder, FileList2(k).name),[WriteDir4 'Test-' sprintf('%.02d.tif', k)]);

2019-08-10 02:57 UTC, samiradaneshgar commented on src/training/randselect_pretraining.m
> +%rmdir('tiling/tiled-multi-page-image','s')
rmdir('../tiling/tiled-multi-page-image','s')

2019-08-10 02:57 UTC, samiradaneshgar commented on src/training/randselect_pretraining.m
> +%rmdir('tiling/tiled-multi-page-river-mask','s')
rmdir('../tiling/tiled-multi-page-river-mask','s')

2019-08-20 20:31 UTC, bspitzbart commented
Who is best to make the requested changes? Samira (owns code), Giannis (owns PR), or Brad (has the most time). I am happy to do it, just checking to see if anything has been started.  This should be an easy merge.

2019-08-20 20:33 UTC, iparask commented
That would be me, since I opened this PR.

2019-09-18 17:47 UTC, samiraucsb approved these changes

2019-09-18 17:47 UTC, merged